sudo: false
language: python
cache: pip

env:
- PYTHON_VERSION=3.6
- PYTHON_VERSION=3.7
jobs:
  include:
    - stage: deploy
      env: PYTHON_VERSION=3.7
      script:
        - source activate test-environment
        - coverage run --source=abpytools setup.py test
      after_success:
        - coveralls
      provider: pypi
      user: gf712
      password:
        secure: h/mcmMMuaGLCuy1FY1Hjbl82AqPe62lK35BbJcvq+bJFtp3sE5FFB2k7LibWqhDBdrsmw0MPsnzBysloGMMHoK2S7ExG5bMlBa6Px2zKpHwY+qqoYMYk23qEPn8dVcEronSfQwQxhJmM0vnyE+sQ7NcinXwJZep4Hx+zdVwsXT0aYZoZImVjFv/YjGWK0epqHQoBf1MCy8aKlFbLvE4lgWcYEtqI4PJgIumLs3lmCcBoHirWGmeyG4VO/9CAOkgBTcUi66+PBe/WLCZj/4DqLJa7VbZXisP71F3zWdjyVXE6zXhCjpXxZvkgF0Eb9CkdPz4MTW9D9LkW10uL6BSZwNiXPVo2FU4Wdax6Ldei+qNrwWoDS48C8btJwgQC8a+aXTQR+EInpIiWvdCuFn4iYSqN7RUHgn6xPMHO0jfY16lxI1Ujqemhysr1H1hDBgnq7tqE4cRvPZS35+pqIkNj1D/DBFC64ehi016N/3BhiFHxeWe+gdMLJdYQhCkLEdISiGTAtHalOUHRXPI7StQ5Ms+YUyDK2RWkhDEsMWnl7rdnpJDG5+go2cVfUuomijSSFNzhbxl1RMz+MU8D6gE6cs7uD6jl4mSYlQlpy3PbtsQRdgJkh/iUzdB20C3on6onpxY+eyvnRiQ3Wna8MrqlRncDYKcENufTwFPpKoJ97rw=
      on:
        branch: master
    - stage: build docs
      env: PYTHON_VERSION=3.7
      script:
        - scripts/build_docs.sh
      provider: pages
      skip_cleanup: true
      github_token: $GITHUB_TOKEN
      keep-history: true
      on:
        branch: master
      local_dir: docs/_build/html/

script:
  - source activate test-environment
  - python setup.py test
install:
  - sh scripts/travis_install.sh
before_script:
  - sh scripts/prepare_python_test.sh
