sudo: false
language: python

env:
- PYTHON_VERSION=3.6
- PYTHON_VERSION=3.7
jobs:
  include:
    - stage: deploy
      env: PYTHON_VERSION=3.7
      script: skip
      before_script: skip
      deploy:
        provider: pypi
        user: gf712
        password:
          secure: h/mcmMMuaGLCuy1FY1Hjbl82AqPe62lK35BbJcvq+bJFtp3sE5FFB2k7LibWqhDBdrsmw0MPsnzBysloGMMHoK2S7ExG5bMlBa6Px2zKpHwY+qqoYMYk23qEPn8dVcEronSfQwQxhJmM0vnyE+sQ7NcinXwJZep4Hx+zdVwsXT0aYZoZImVjFv/YjGWK0epqHQoBf1MCy8aKlFbLvE4lgWcYEtqI4PJgIumLs3lmCcBoHirWGmeyG4VO/9CAOkgBTcUi66+PBe/WLCZj/4DqLJa7VbZXisP71F3zWdjyVXE6zXhCjpXxZvkgF0Eb9CkdPz4MTW9D9LkW10uL6BSZwNiXPVo2FU4Wdax6Ldei+qNrwWoDS48C8btJwgQC8a+aXTQR+EInpIiWvdCuFn4iYSqN7RUHgn6xPMHO0jfY16lxI1Ujqemhysr1H1hDBgnq7tqE4cRvPZS35+pqIkNj1D/DBFC64ehi016N/3BhiFHxeWe+gdMLJdYQhCkLEdISiGTAtHalOUHRXPI7StQ5Ms+YUyDK2RWkhDEsMWnl7rdnpJDG5+go2cVfUuomijSSFNzhbxl1RMz+MU8D6gE6cs7uD6jl4mSYlQlpy3PbtsQRdgJkh/iUzdB20C3on6onpxY+eyvnRiQ3Wna8MrqlRncDYKcENufTwFPpKoJ97rw=
        on:
          tags: true
          # only deploy release versions
          condition: $TRAVIS_TAG =~ ^v\d+\.\d+\.\d+$
    - stage: build docs
      env: PYTHON_VERSION=3.7
      before_script: skip
      script:
        - source scripts/build_docs.sh
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep-history: true
        on:
          tags: true
          # only deploy release versions
          condition: $TRAVIS_TAG =~ ^v\d+\.\d+\.\d+$
        local_dir: docs/_build/html/

script:
  - coverage run --source=abpytools setup.py test
  - coveralls
install:
  - source scripts/travis_install.sh
before_script:
  - source scripts/prepare_python_test.sh
