sudo: false

language: python

python:
    - 3.4
    - 3.5
    - 3.6

# Install packages
install:
    # install numpy using binaries to speed up process
    - pip install --upgrade pip setuptools wheel
    - pip install --only-binary=numpy numpy
    - python setup.py install

script:
    - python setup.py test